### ISSUE TITLE
Option to affect all comps / all precomps from current

### ISSUE THREAD

**Issue by Nico-Duduf** [RxLaboratory/DuGR#15]

**Comment by LarsJandel** [comment]
+1
Just bumping as this enhancement would be handy in my current project.
In my case, I have a custom named group which exists in multiple comps, which I would like to affect project wide.
Your 2nd idea, all precomps from current, sounds great as well!
Thanks

**Comment by Nico-Duduf** [comment]
Done!
Available in 5.1.0 very soon

**Comment by LarsJandel** [comment]
Fantastic - thanks as always! 🙏
