### ISSUE TITLE
[FEATURE REQUEST] Some GUI options

### ISSUE THREAD

**Issue by JFMugen** [RxLaboratory/DuGR#37]
I ask this mainly to have a bigger space for groups. 

I think this line is required, so it is good as it is

![image](https://user-images.githubusercontent.com/61559703/129036224-c8d60b8f-7630-4eed-84d6-d89bcca7ffce.png)

But I personally wouldn't use this line, so having an option to hide it would be nice. 

![image](https://user-images.githubusercontent.com/61559703/129036389-0e4dd10b-567f-44de-ac88-1eff22a09e46.png)

I think this line can be hidden as well. We can choose a default in settings (prop. or groups) and hide the line. 

![image](https://user-images.githubusercontent.com/61559703/129036586-8829b993-1e82-4b05-b361-dc231b163dce.png)

Lastly, this is a minor thing, but I think it would be better if we can remove default groups. 

Thank you for the tool : )

**Comment by Nico-Duduf** [comment]
will be in DuGR 5.0 in a few days
