### ISSUE TITLE
[FEATURE REQUEST] secondry filter

### ISSUE THREAD

**Issue by msongz** [RxLaboratory/DuGR#39]
**Is your feature request related to a problem? Please describe.**
lets say i have 6 text layers, 3 of them are not visible
now I can filter them out by choosing "type:texts" , showing 6 text layers
but can not filter the texts layer which are not visible, that 3 layers.

**Describe the solution you'd like**
now the list can be multi-highlighted, just show layers which only fit with highlighted conditions?
![image](https://user-images.githubusercontent.com/2059694/132196382-b3726f5e-d138-41bd-ac6c-65b974009b2a.png)

with these setting, will show only that 3 visible layers i think.

**Comment by Nico-Duduf** [comment]
Thanks for the feedback!
DuGR should do that (although I think there actually is a bug),
but I have to add another option, to let users select either `texts AND visible` or `text OR visible`...

**Comment by Nico-Duduf** [comment]
Done in 5.0.0 available in a few days
