### ISSUE TITLE
Dugr - more attributes to filter the current comp

### ISSUE THREAD

**Issue by freshmograph** [RxLaboratory/DuGR#44]
**Is your feature request related to a problem? Please describe.**
There are other unique layer properties that would be a great addition to Dugr.

**Describe the solution you'd like**
I would love to see additional filters to select layers. The additions would be **layers at the CTI, layers that are within the preview range, layers that have a mask, layers with a matte, and layers with keyframes**.

**Describe alternatives you've considered**
The combination of settings in Dugr now doesn't allow for the options mentioned above.

**Additional context**
Thank you for your consideration.

**Comment by Nico-Duduf** [comment]
Hi,
Thanks for the suggestion, that's a good idea.
I don't know when we'll be able to implement it but it's now in the todo list.

**Comment by Nico-Duduf** [comment]
done in DuGR 5.0 available in a few days
