### ISSUE TITLE
[FEATURE REQUEST] Layer Styles

### ISSUE THREAD

**Issue by msongz** [RxLaboratory/DuGR#45]
<img width="367" alt="image" src="https://user-images.githubusercontent.com/2059694/165442195-39f8daa6-12aa-4870-99d9-adfe4eced56c.png">

add ability to sort layers with Layer Styles enabled
would be better we could sort different kind of layer styles effects like: outer glow, inner glow, etc.

**Comment by Nico-Duduf** [comment]
adding this to the 4.1 milestone ;)
I'll do that as soon as Duik Ángela goes to beta, quite soon

**Comment by Nico-Duduf** [comment]
Done, will be in 4.1 available in a few days
