### ISSUE TITLE
[FEATURE REQUEST] Auto select groups

### ISSUE THREAD

**Issue by freshmograph** [RxLaboratory/DuGR#47]
**Is your feature request related to a problem? Please describe.**
It would be great if there was a setting to autoselect layers.

**Describe the solution you'd like**
I would like to click on a property type and have Dugr select the layers automatically instead of having to click the Select Layers icon.

**Describe alternatives you've considered**
Setting the interactive mode (sticky) is close to what I want, but many times I just want to select the layers without isolating them.

**Additional context**
Thank you for your consideration.

**Comment by Nico-Duduf** [comment]
We'll have to make sure this would not in some way break other features, but it seems a good idea, at least as an option.

**Comment by Nico-Duduf** [comment]
It will be in 4.1 available in a few days
