### ISSUE TITLE
Subgroups

### ISSUE THREAD

**Issue by The-2048** [RxLaboratory/DuGR#55]
Hi, i would like to suggest a function for DUGR
Add **subgroups** to be able to select them individually
<img alt="image" width="367" src="https://i.ibb.co/CBfSbGr/Untitled.png">

**Comment by Nico-Duduf** [comment]
This can't be done with the current UI tools provided by After Effects and the way DuGR is coded.

But you can select both the character and "subgroup" in the list, that'd work the same way as your proposal
